### ISSUE TITLE
Custom Status

### ISSUE THREAD

**Issue by lugart** [JakyeRU/SteamIdler#12]
Hi, in the line client.setPersona I can change the status Online to Offline, etc.

But, can I put my custom status somewhere by fixing the code a bit? Or it is not provided?

**Comment by JakyeRU** [comment]
Hello,

Adding a custom status will require you to play a non-steam game. For
example:
```js
client.gamesPlayed("My custom status");
```

**Comment by ValentinNeaga** [comment]
Hello @lugart,

Adding a custom status can be achieved by playing a custom game.
For example:
```js
client.gamesPlayed("My custom status");
```

**Comment by lugart** [comment]
1 more question. 
How do I boost hours in games and have my custom status at the same time?

If I change to client.gamesPlayed("My custom status"); then the status works, but none of the games actually spin. Tried adding another line, then it crashes or just doesn't work.

Can you tell me if you know if it is possible to have both games variable and your "custom status"?

**Comment by ValentinNeaga** [comment]
I haven't tested it but it could work if you provide an array with both, your custom game and the games that need to be idled.

```js
client.gamesPlayed(games.unshift("Custom status"));
```

**Comment by tomastaker** [comment]
> I haven't tested it but it could work if you provide an array with both, your custom game and the games that need to be idled.
> 
> ```js
> client.gamesPlayed(games.unshift("Custom status"));
> ```

Tried your offer, but it works very strangely)) 

In the profile shows custom status, but game hourboost does not work)) 
It feels like the status cancels the launch of games

Bro, thanks for responding)

**Comment by ValentinNeaga** [comment]
Then I'm not really sure if it is possible to play both, a non-steam game and a steam game at the same time.
